code = sprintf(['function ports = getSubsystemPorts(subsystemHandle)\n', ...
'if nargin < 1 || isempty(subsystemHandle), subsystemHandle = gcbh; end\n', ...
'if isempty(subsystemHandle) || ~isnumeric(subsystemHandle) || ~isscalar(subsystemHandle) || subsystemHandle <= 0\n', ...
'    error(''getSubsystemPorts:NoSelection'', ''Select a subsystem block first.'');\n', ...
'end\n', ...
'if ~strcmp(get_param(subsystemHandle, ''BlockType''), ''SubSystem'')\n', ...
'    error(''getSubsystemPorts:NotSubsystem'', ''Selected block is not a subsystem.'');\n', ...
'end\n', ...
'opts = {''LookUnderMasks'', ''on'', ''FollowLinks'', ''on'', ''SearchDepth'', 1};\n', ...
'inH = find_system(subsystemHandle, opts{:}, ''BlockType'', ''Inport'');\n', ...
'outH = find_system(subsystemHandle, opts{:}, ''BlockType'', ''Outport'');\n', ...
'ports = struct(''Handle'', double(subsystemHandle), ''Path'', getfullname(subsystemHandle), ...\n', ...
'    ''InportNames'', {normNames(inH)}, ''OutportNames'', {normNames(outH)});\n', ...
'end\n\n', ...
'function n = normNames(h)\n', ...
'if isempty(h), n = {}; return; end\n', ...
'n = get_param(h, ''Name'');\n', ...
'if ischar(n), n = {n}; end\n', ...
'n = unique(cellfun(@strtrim, n(~cellfun(''isempty'', n)), ''UniformOutput'', false), ''stable'');\n', ...
'n = n(:).'';\n', ...
'end\n']);

fid = fopen('getSubsystemPorts.m', 'wt', 'n', 'UTF-8');
fwrite(fid, code);
fclose(fid);
fprintf('Successfully created getSubsystemPorts.m on disk!\n');